namespace OilCore.Enumerations;

public enum MichiganCounty
{
    Unknown,
    Alcona,
    Alger,
    Allegan,
    Alpena,
    Antrim,
    Arenac,
    Baraga,
    Barry,
    Bay,
    Benzie,
    Berrien,
    Branch,
    Calhoun,
    Cass,
    Charlevoix,
    Cheboygan,
    Chippewa,
    Clare,
    Clinton,
    Crawford,
    Delta,
    Dickinson,
    Eaton,
    Emmet,
    Genesee,
    Gladwin,
    Gogebic,
    GrandTraverse,
    Gratiot,
    Hillsdale,
    Houghton,
    Huron,
    Ingham,
    Ionia,
    Iosco,
    Iron,
    Isabella,
    Jackson,
    Kalamazoo,
    Kalkaska,
    Kent,
    Keweenaw,
    Lake,
    Lapeer,
    Leelanau,
    Lenawee,
    Livingston,
    Luce,
    Mackinac,
    Macomb,
    Manistee,
    Marquette,
    Mason,
    Mecosta,
    Menominee,
    Midland,
    Missaukee,
    Monroe,
    Montcalm,
    Montmorency,
    Muskegon,
    Newaygo,
    Oakland,
    Oceana,
    Ogemaw,
    Ontonagon,
    Osceola,
    Oscoda,
    Otsego,
    Ottawa,
    PresqueIsle,
    Roscommon,
    Saginaw,
    Sanilac,
    Schoolcraft,
    Shiawassee,
    StClair,
    StJoseph,
    Tuscola,
    VanBuren,
    Washtenaw,
    Wayne,
    Wexford
}

public static class MichiganCountyExtensions
{
    public static string ToDisplayName(this MichiganCounty county)
    {
        return county switch
        {
            MichiganCounty.GrandTraverse => "Grand Traverse",
            MichiganCounty.PresqueIsle => "Presque Isle",
            MichiganCounty.StClair => "St. Clair",
            MichiganCounty.StJoseph => "St. Joseph",
            _ => county.ToString()
        };
    }
}
