using OilCore.Utilities;

namespace OilCore.Enumerations;

public enum UsState
{
    [Abbreviation("--")] Unknown,
    [Abbreviation("AL")] Alabama,
    [Abbreviation("AK")] Alaska,
    [Abbreviation("AZ")] Arizona,
    [Abbreviation("AR")] Arkansas,
    [Abbreviation("CA")] California,
    [Abbreviation("CO")] Colorado,
    [Abbreviation("CT")] Connecticut,
    [Abbreviation("DE")] Delaware,
    [Abbreviation("FL")] Florida,
    [Abbreviation("GA")] Georgia,
    [Abbreviation("HI")] Hawaii,
    [Abbreviation("ID")] Idaho,
    [Abbreviation("IL")] Illinois,
    [Abbreviation("IN")] Indiana,
    [Abbreviation("IA")] Iowa,
    [Abbreviation("KS")] Kansas,
    [Abbreviation("KY")] Kentucky,
    [Abbreviation("LA")] Louisiana,
    [Abbreviation("ME")] Maine,
    [Abbreviation("MD")] Maryland,
    [Abbreviation("MA")] Massachusetts,
    [Abbreviation("MI")] Michigan,
    [Abbreviation("MN")] Minnesota,
    [Abbreviation("MS")] Mississippi,
    [Abbreviation("MO")] Missouri,
    [Abbreviation("MT")] Montana,
    [Abbreviation("NE")] Nebraska,
    [Abbreviation("NV")] Nevada,
    [Abbreviation("NH")] NewHampshire,
    [Abbreviation("NJ")] NewJersey,
    [Abbreviation("NM")] NewMexico,
    [Abbreviation("NY")] NewYork,
    [Abbreviation("NC")] NorthCarolina,
    [Abbreviation("ND")] NorthDakota,
    [Abbreviation("OH")] Ohio,
    [Abbreviation("OK")] Oklahoma,
    [Abbreviation("OR")] Oregon,
    [Abbreviation("PA")] Pennsylvania,
    [Abbreviation("RI")] RhodeIsland,
    [Abbreviation("SC")] SouthCarolina,
    [Abbreviation("SD")] SouthDakota,
    [Abbreviation("TN")] Tennessee,
    [Abbreviation("TX")] Texas,
    [Abbreviation("UT")] Utah,
    [Abbreviation("VT")] Vermont,
    [Abbreviation("VA")] Virginia,
    [Abbreviation("WA")] Washington,
    [Abbreviation("WV")] WestVirginia,
    [Abbreviation("WI")] Wisconsin,
    [Abbreviation("WY")] Wyoming,

    // Territories
    [Abbreviation("DC")] DistrictOfColumbia,
    [Abbreviation("AS")] AmericanSamoa,
    [Abbreviation("GU")] Guam,
    [Abbreviation("MP")] NorthernMarianaIslands,
    [Abbreviation("PR")] PuertoRico,
    [Abbreviation("VI")] USVirginIslands,
    [Abbreviation("UM")] USMinorOutlyingIslands
}
